source 'https://rubygems.org'

gem 'rails', '3.2.12'

gem 'activerecord-jdbcpostgresql-adapter'
gem 'postgres_ext'

gem 'foreigner'
gem 'devise'
gem 'omniauth-facebook'
gem 'kaminari'
gem 'cells'

gem 'rails-i18n'
gem 'devise-i18n'

gem 'nokogiri'

gem 'haml'
gem 'high_voltage'
gem 'kramdown'

gem 'puma'

group :assets do
  gem 'zurb-foundation', '~> 4.1.6'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyrhino'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'railroady'
  gem 'rspec-rails'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
